### ISSUE TITLE
Photo Resize issue. - Photos are not at a standard upload size

### ISSUE THREAD

**Issue by RAGING3K** [Brockify/FindMyPeepsApp#2]
Close to a solution

**Comment by Brockify** [comment]
Sent a potential enhancement on skype. Can implement whenever.

**Comment by RAGING3K** [comment]
Currently set to standard size of 100x100. Agreed with enhancement stated on skype. Will be implimented in near future.

**Comment by RAGING3K** [comment]
Closed for now, will come back to in future
