### ISSUE TITLE
Profile pic

### ISSUE THREAD

**Issue by Brockify** [Brockify/FindMyPeepsApp#26]
Profile pic isn't showing up on the profile page for my account - Brockify -

**Comment by Brockify** [comment]
Potential fix, the user variable is their original username so I think before getting profile picture .toLower();

**Comment by RAGING3K** [comment]
Got it resolved. Fixed by instead of having it saved as image filename from phone. I have two different saves one username.jpg (This gets 100x100 resize) Other as usernameorig.jpg. Should work now
